version: "3.7"
services:
  api:
    container_name: api
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
      - DB_NAME=bewise

  db:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bewise
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
