version: "3.7"
services:
  api:
    build: .
    container_name: bewise-api
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOSTNAME=bewise-db
      - DB_PORT=5432
      - DB_NAME=bewise
    restart: always

  db:
    image: postgres
    container_name: bewise-db
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bewise
    ports:
      - 5432:5432
    volumes:
      - bewise-postgres-db:/var/lib/postgresql/data

volumes:
  bewise-postgres-db:
